/**
 * Default seed data for initial setup and offline demo mode
 */

export const INITIAL_HOUSE_SETTINGS = {
  houseName: 'Greenwood Student Residency',
  electricityRate: 10, // ₹10 per unit
  currency: '₹',
  contactPhone: '+91 98765 43210',
  upiId: 'greenwood.residency@upi',
  upiQrUrl: '',
  address: '14/B University Road, Near North Campus',
};

export const INITIAL_USERS = [
  {
    uid: 'admin_001',
    name: 'Rajesh Sharma',
    email: 'admin@rental.com',
    role: 'admin',
    phone: '+91 98765 43210',
    createdAt: new Date('2026-01-01').toISOString(),
  },
  {
    uid: 'student_101',
    name: 'Aarav Gupta',
    email: 'aarav@student.com',
    role: 'student',
    roomNumber: '101',
    phone: '+91 98111 22233',
    baseRent: 4500,
    status: 'active',
    createdAt: new Date('2026-02-01').toISOString(),
  },
  {
    uid: 'student_102',
    name: 'Priya Verma',
    email: 'priya@student.com',
    role: 'student',
    roomNumber: '102',
    phone: '+91 98222 33344',
    baseRent: 4500,
    status: 'active',
    createdAt: new Date('2026-02-01').toISOString(),
  },
  {
    uid: 'student_201',
    name: 'Rohan Roy',
    email: 'rohan@student.com',
    role: 'student',
    roomNumber: '201',
    phone: '+91 98333 44455',
    baseRent: 5000,
    status: 'active',
    createdAt: new Date('2026-03-01').toISOString(),
  },
];

export const INITIAL_PAYMENTS = [
  {
    id: 'pay_001',
    studentId: 'student_101',
    studentName: 'Aarav Gupta',
    roomNumber: '101',
    month: 'August',
    year: 2026,
    rentAmount: 4500,
    electricityUnits: 42,
    unitRate: 10,
    electricityAmount: 420,
    otherAmount: 100, // maintenance
    totalAmount: 5020,
    paymentMode: 'upi',
    transactionId: 'UPI492819382109',
    receiptUrl: '',
    status: 'approved',
    adminRemarks: 'Payment verified and credited to bank.',
    createdAt: new Date('2026-08-04T10:30:00').toISOString(),
    approvedAt: new Date('2026-08-05T09:15:00').toISOString(),
  },
  {
    id: 'pay_002',
    studentId: 'student_102',
    studentName: 'Priya Verma',
    roomNumber: '102',
    month: 'September',
    year: 2026,
    rentAmount: 4500,
    electricityUnits: 55,
    unitRate: 10,
    electricityAmount: 550,
    otherAmount: 100,
    totalAmount: 5150,
    paymentMode: 'gpay',
    transactionId: 'GPAY7712398451',
    receiptUrl: '',
    status: 'approved',
    adminRemarks: 'Payment received.',
    createdAt: new Date('2026-09-02T14:20:00').toISOString(),
    approvedAt: new Date('2026-09-02T16:00:00').toISOString(),
  },
  {
    id: 'pay_003',
    studentId: 'student_101',
    studentName: 'Aarav Gupta',
    roomNumber: '101',
    month: 'September',
    year: 2026,
    rentAmount: 4500,
    electricityUnits: 38,
    unitRate: 10,
    electricityAmount: 380,
    otherAmount: 100,
    totalAmount: 4980,
    paymentMode: 'phonepe',
    transactionId: 'PP994827103284',
    receiptUrl: '',
    status: 'pending',
    adminRemarks: '',
    createdAt: new Date('2026-09-06T11:00:00').toISOString(),
  },
  {
    id: 'pay_004',
    studentId: 'student_201',
    studentName: 'Rohan Roy',
    roomNumber: '201',
    month: 'August',
    year: 2026,
    rentAmount: 5000,
    electricityUnits: 65,
    unitRate: 10,
    electricityAmount: 650,
    otherAmount: 150,
    totalAmount: 5800,
    paymentMode: 'upi',
    transactionId: 'UPI0000123INVALID',
    receiptUrl: '',
    status: 'rejected',
    adminRemarks: 'Transaction reference is invalid. Please double-check bank debited UTR and resubmit.',
    createdAt: new Date('2026-08-07T18:45:00').toISOString(),
  },
];

export const INITIAL_NOTICES = [
  {
    id: 'not_001',
    title: 'Water Tank Cleaning & Maintenance',
    content: 'All overhead water tanks will be sanitized this Saturday between 10:00 AM and 2:00 PM. Please store sufficient drinking water.',
    priority: 'urgent',
    createdAt: new Date('2026-09-18T10:00:00').toISOString(),
    author: 'Rajesh Sharma (Landlord)',
  },
  {
    id: 'not_002',
    title: 'Reminder: Monthly Rent & Meter Submission Deadline',
    content: 'Please submit your monthly rent and electricity units reading by the 7th of every month to avoid late convenience charges.',
    priority: 'normal',
    createdAt: new Date('2026-09-01T08:00:00').toISOString(),
    author: 'Rajesh Sharma (Landlord)',
  },
  {
    id: 'not_003',
    title: 'High-Speed Wi-Fi Router Upgraded',
    content: 'New 5GHz mesh router installed on Floor 1 & 2 for better connectivity during study hours. Password remains unchanged.',
    priority: 'normal',
    createdAt: new Date('2026-08-20T12:00:00').toISOString(),
    author: 'Rajesh Sharma (Landlord)',
  },
];

export const INITIAL_COMPLAINTS = [
  {
    id: 'comp_001',
    studentId: 'student_101',
    studentName: 'Aarav Gupta',
    roomNumber: '101',
    category: 'plumbing',
    title: 'Washroom tap dripping continuously',
    description: 'The cold water tap in Room 101 washroom is dripping continuously even when shut tightly.',
    status: 'in_progress',
    adminReply: 'Plumber scheduled to inspect tomorrow morning at 11 AM.',
    createdAt: new Date('2026-09-15T15:20:00').toISOString(),
  },
  {
    id: 'comp_002',
    studentId: 'student_102',
    studentName: 'Priya Verma',
    roomNumber: '102',
    category: 'electrical',
    title: 'Study desk power socket loose',
    description: 'The wall switchboard near the study table sparks intermittently when plugging in laptop charger.',
    status: 'resolved',
    adminReply: 'Electrician replaced the modular switchboard on Sept 17.',
    createdAt: new Date('2026-09-16T09:30:00').toISOString(),
  },
];

